name: FleetOps-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Java
        run: mvn clean package -DskipTests

      - name: Install C++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasio-dev nlohmann-json3-dev

      - name: Build C++ Engine
        run: |
          cd route-engine
          g++ main.cpp -o engine -lpthread

      - name: Verify Docker Compose
        run: docker-compose build